### ISSUE TITLE
nullable type syntax prevents Unity compilation

### ISSUE THREAD

**Issue by timsgardner** [nasser/magic#105]
The C# 8 nullable type syntax in `Binder.cs` prevents compilation in Unity.

This can be alleviated by removing the `?` syntax from `Binder.cs`, however this syntax is useful for development outside of Unity. Possible solutions include preprocessor directives, exactly how best to do that is an open question and needs some thought.

For now I've pushed a fix to [the unity branch](https://github.com/timsgardner/magic/tree/unity) on my fork.

**Comment by nasser** [comment]
Should be fixed by 4f5a445148fce819f64d3422f50f26254b50ec85
