### ISSUE TITLE
Package spec.alpha in all releases

### ISSUE THREAD

**Issue by nasser** [nasser/magic#209]
`clojure.spec.alpha` and `clojure.spec.gen.alpha` do not seem to be available in Magic.Unity.

**Comment by nasser** [comment]
Working outside of Unity as of nasser/nostrand@7e70d3348ee04d2af7f8794aeff928a172570868. Need to verify Magic.Unity next,

**Comment by cjbarre** [comment]
I cloned Magic.Unity and followed the overview procedures. I was able to compile a simple namespace with no requires successfully.

I can confirm that when compiling a simple namespace such as:

```clojure
(ns game.core
  (:require [clojure.spec.alpha :as spec]
            [clojure.spec.gen.alpha :as spec-gen]))
```

Neither namespace can be found and an error is output for both.

Thoughts on why?

**Comment by cjbarre** [comment]
The 1.0 release fails the same way.

**Comment by nasser** [comment]
I am able to reproduce this on my end in Unity. dropping in the built DLLs from nostrand does not fix the problem. It does not make any sense, frankly. I will keep digging...

**Comment by skydread1** [comment]
Just a follow up on that one.

## What works

building a full clojure project containing `specs` and `pprint` with `nostrand` works fine.

## What does not work

In Unity, the above mentioned error is still there.
The current work around is to ignore pprint and specs which is a pity.

Any news on this ?

**Comment by nasser** [comment]
I have not been able to revisit this since reproducing. I will try and make time for it in the coming month.

**Comment by skydread1** [comment]
## Solution

Refer to [PR8](https://github.com/nasser/Magic.Unity/pull/8) in `Magic.Unity` repo.

**Comment by nasser** [comment]
Merged :v:
