### ISSUE TITLE
`sort` with a custom comparator does not have the expected behaviour

### ISSUE THREAD

**Issue by skydread1** [nasser/magic#221]
## Problem

If we use the default comparator of `sort`, which is `compare`, we have the expected result.

For instance:
```clojure
user> (sort #(compare %2 %1) [1 3 2])                       
(3 2 1)
```

However, with a custom comparator, we don't have the expected result.

For instance, to sort in descending order:
```clojure
;; in jvm (using emacs cider repl)
user> (sort > [1 3 2]) 
(3 2 1)

;; in magic (using nostrand repl)
user> (sort > [1 3 2]) 
(1 2 3)
```

**Comment by nasser** [comment]
i can confirm the same results on my end. this seems to be a bug in the ClojureCLR implementation of the comparison abstraction. [this implementation](https://github.com/nasser/Clojure.Runtime/blob/clojure.runtime/Clojure/Lib/RT.cs#L3458-L3461) seems wrong to me. i would expect it to try and convert to `IComparer` at the very least (which our functions support) and fall back on logic similar to [this](https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/AFunction.java#L50-L61) but that all seems missing for no good reason.

i will work on a patch against the Clojure.Runtime repo. in the meantime the following workaround seems to hold:

```
user> (sort (comparator <) [1 3 2])
(1 2 3)
user> (sort (comparator >) [1 3 2])
(3 2 1)
```
