### ISSUE TITLE
I cannot bootstrap stdlib namespaces

### ISSUE THREAD

**Issue by skydread1** [nasser/magic#230]
## Problem

After the last improvements, when I run the nostrand command in the magic repo:
```
nos build/bootstrap
```
Only the following namespaces are being compiles and added to the `bootstrap` folder:
```
clojure.core.clj.dll                              magic.analyzer.analyze_host_forms.clj.dll
clojure.tools.analyzer.ast.clj.dll                magic.analyzer.typed_passes.clj.dll
clojure.tools.analyzer.clj.dll                    magic.analyzer.types.clj.dll
clojure.tools.analyzer.env.clj.dll                magic.analyzer.untyped_passes.clj.dll
clojure.tools.analyzer.passes.cleanup.clj.dll     magic.core.clj.dll
clojure.tools.analyzer.passes.clj.dll             magic.flags.clj.dll
clojure.tools.analyzer.passes.elide_meta.clj.dll  magic.interop.clj.dll
clojure.tools.analyzer.passes.source_info.clj.dll magic.intrinsics.clj.dll
clojure.tools.analyzer.passes.trim.clj.dll        magic.util.clj.dll
clojure.tools.analyzer.utils.clj.dll
```
Missing namespaces:
- all `stdlib` namespaces excepted `clojure.core`
## Note

- Compiling `clojure.core` first or last does not matter (so the forward declare is actually not needed in my case).
- The other namespace are just ignore but reach the `clojure.core/compile` function body though but nothing happen.
- It is not a nostrand bug as the compilation works well for all our personal Clojure libraries.

## Related issue

It seems related to #207 but the outcome is the opposite.

**Comment by skydread1** [comment]
## Update

Deleting the git repo totally and cloning again fixed the issue.

I am wondering if the fact that when we put `clojure.core` first, it only compiles it and ignores all the other nses, is related to a caching problem. The nses seem to be ignored because present somewhere I suppose hence the cache guess.

**Comment by nasser** [comment]
Unfortunately the design of Clojure's compilation machinery overlaps with its `require` machinery. Whether or not a namespace has already been required can affect whether or not a file will be written to disk. The MAGIC API has some workarounds for this but the results are not consistent. I may need to rewrite the `bootstrap` to directly compile the files using our internal APIs and not `clojure.core/compile`.
